### ISSUE TITLE
error[org.apache.qpid.proton.engine.TransportException: connection aborted]

### ISSUE THREAD

**Issue by aj-devops-wi** [logstash-plugins/logstash-input-azure_event_hubs#19]
When attempting to utilize the logstash-input-azure_event_hubs, I'm seeing the following error.  This is on Logstash 6.4.  Any thoughts?  Verified that there are no firewalls in this traffic path.

```
[2018-09-26T18:28:58,552][DEBUG][logstash.inputs.azureeventhubs] Exploded Event Hub configuration. {:event_hubs_exploded=>"[{\"event_hubs\"=>[\"my-eventhub-name\"], \"event_hub_connections\"=>[<password>], \"consumer_group\"=>\"logstash-reader\", \"storage_connection\"=><password>, \"decorate_events\"=>true, \"tags\"=>[\"azureeventhublogs\", \"sharedazurelogs\"], \"threads\"=>5, \"enable_metric\"=>true, \"codec\"=><LogStash::Codecs::Plain id=>\"plain_2888218f-cea2-4e6e-954b-195be610c9c6\", enable_metric=>true, charset=>\"UTF-8\">, \"add_field\"=>{}, \"config_mode\"=>\"basic\", \"max_batch_size\"=>125, \"prefetch_count\"=>300, \"receive_timeout\"=>60, \"initial_position\"=>\"beginning\", \"initial_position_look_back\"=>86400, \"checkpoint_interval\"=>5}]"}
[2018-09-26T18:28:58,586][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"main", :thread=>"#<Thread:0x5d94020d run>"}
[2018-09-26T18:28:58,938][INFO ][logstash.inputs.azureeventhubs] Event Hub my-eventhub-name is initializing...
[2018-09-26T18:28:58,993][INFO ][com.microsoft.azure.eventprocessorhost.EventProcessorHost] host logstash-109e7dd8-05d8-47a1-a441-972c0e27a1ae: New EventProcessorHost created.
[2018-09-26T18:28:59,006][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2018-09-26T18:28:59,038][DEBUG][logstash.inputs.azureeventhubs] If this is the initial read... Configuring Event Hub my-eventhub-name to read events all events.
[2018-09-26T18:28:59,273][INFO ][com.microsoft.azure.eventprocessorhost.EventProcessorHost] host logstash-109e7dd8-05d8-47a1-a441-972c0e27a1ae: Starting event processing.
[2018-09-26T18:28:59,321][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2018-09-26T18:28:59,322][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
[2018-09-26T18:28:59,368][DEBUG][logstash.agent           ] Starting puma
[2018-09-26T18:28:59,401][INFO ][com.microsoft.azure.eventhubs.impl.MessagingFactory] messagingFactory[MessagingFactory077d9c], hostName[my-eventhub-name.servicebus.windows.net], info[starting reactor instance.]
[2018-09-26T18:28:59,420][INFO ][com.microsoft.azure.eventhubs.impl.ReactorHandler] reactor.onReactorInit
[2018-09-26T18:28:59,509][DEBUG][logstash.agent           ] Trying to start WebServer {:port=>9600}
[2018-09-26T18:28:59,789][WARN ][com.microsoft.azure.eventhubs.impl.ConnectionHandler] onTransportClosed: hostname[my-eventhub-name.servicebus.windows.net:5671], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
[2018-09-26T18:28:59,802][INFO ][com.microsoft.azure.eventhubs.impl.ConnectionHandler] onConnectionUnbound: hostname[my-eventhub-name.servicebus.windows.net:5671], state[ACTIVE], remoteState[UNINITIALIZED]
[2018-09-26T18:28:59,798][ERROR][com.microsoft.azure.eventprocessorhost.PartitionManager] host logstash-109e7dd8-05d8-47a1-a441-972c0e27a1ae: Exception while initializing stores, not starting partition manager
com.microsoft.azure.eventhubs.EventHubException: org.apache.qpid.proton.engine.TransportException: connection aborted
        at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:58) ~[azure-eventhubs-1.0.1.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessagingFactory.onConnectionError(MessagingFactory.java:241) ~[azure-eventhubs-1.0.1.jar:?]
        at com.microsoft.azure.eventhubs.impl.ConnectionHandler.onTransportError(ConnectionHandler.java:105) ~[azure-eventhubs-1.0.1.jar:?]
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.27.1.jar:?]
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.27.1.jar:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.27.1.jar:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.27.1.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:462) ~[azure-eventhubs-1.0.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[2018-09-26T18:28:59,822][INFO ][logstash.inputs.azureeventhubs] Event Hub registration complete.  {:event_hub_name=>"my-eventhub-name"}
[2018-09-26T18:28:59,827][ERROR][logstash.inputs.azureeventhubs] Event Hub failure while registering. {:event_hub_name=>"my-eventhub-name", :exception=>java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.EventHubException: org.apache.qpid.proton.engine.TransportException: connection aborted, :backtrace=>["java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)", "java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)", "java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)", "java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)", "java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)", "java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)", "com.microsoft.azure.eventhubs.impl.MessagingFactory.onOpenComplete(MessagingFactory.java:229)", "com.microsoft.azure.eventhubs.impl.MessagingFactory.onConnectionError(MessagingFactory.java:241)", "com.microsoft.azure.eventhubs.impl.ConnectionHandler.onTransportError(ConnectionHandler.java:105)", "org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)", "org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)", "org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)", "org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)", "com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:462)", "java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)", "java.util.concurrent.FutureTask.run(FutureTask.java:266)", "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)", "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)", "java.lang.Thread.run(Thread.java:748)"]}
[2018-09-26T18:28:59,874][ERROR][logstash.inputs.azureeventhubs] Event Hub encountered an error. {:event_hub_name=>"my-eventhub-name", :exception=>java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.EventHubException: org.apache.qpid.proton.engine.TransportException: connection aborted, :backtrace=>["java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)", "java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)", "java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)", "java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)", "java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)", "java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)", "com.microsoft.azure.eventhubs.impl.MessagingFactory.onOpenComplete(MessagingFactory.java:229)", "com.microsoft.azure.eventhubs.impl.MessagingFactory.onConnectionError(MessagingFactory.java:241)", "com.microsoft.azure.eventhubs.impl.ConnectionHandler.onTransportError(ConnectionHandler.java:105)", "org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)", "org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)", "org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)", "org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)", "com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:462)", "java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)", "java.util.concurrent.FutureTask.run(FutureTask.java:266)", "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)", "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)", "java.lang.Thread.run(Thread.java:748)"]}
[2018-09-26T18:28:59,891][INFO ][logstash.inputs.azureeventhubs] Event Hub my-eventhub-name is closed.
```

Input section of conf:
```
input {
    azure_event_hubs {
    event_hub_connections => "Endpoint=sb://my-eventhub-name.servicebus.windows.net/;SharedAccessKeyName=logstash-reader;SharedAccessKey={{ my-eventhub-access-key }};EntityPath=my-eventhub-name"
    threads => 5
    decorate_events => true
    consumer_group => "logstash-reader"
    storage_connection => "DefaultEndpointsProtocol=https;AccountName=logstashscale;AccountKey={{ my-storage-account-key }};EndpointSuffix=core.windows.net"
    tags => ["azureeventhublogs", "sharedazurelogs"]
   }
}
```

**Comment by aj-devops-wi** [comment]
This did end up being a problem with a stateful firewall.
