### ISSUE TITLE
Exception stealing lease

### ISSUE THREAD

**Issue by EmFl** [logstash-plugins/logstash-input-azure_event_hubs#25]
Hello,
I've been having random issues where logstash stops listening to some partitions of the eventhub. Some error that seem to match timestamp is the one below :

Have you seen this previously ? And do you know what could be the cause for this ?

```
[2018-12-07T16:32:07,008][WARN ][com.microsoft.azure.eventprocessorhost.PartitionManager] host logstash-ed014d56-4e6b-440f-a539-da3997da04d1: Exception stealing lease
java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
        at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113) ~[azure-storage-7.0.0.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_191]
        at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.lambda$cachePartitionIds$16(AzureStorageCheckpointLeaseManager.java:477) ~[azure-eventhubs-eph-1.0.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_191]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: com.microsoft.azure.storage.StorageException: The client could not finish the operation within specified maximum execution timeout.
        at com.microsoft.azure.storage.core.ExecutionEngine.setupStorageRequest(ExecutionEngine.java:287) ~[azure-storage-7.0.0.jar:?]
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:80) ~[azure-storage-7.0.0.jar:?]
        at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:109) ~[azure-storage-7.0.0.jar:?]
        ... 10 more
Caused by: java.util.concurrent.TimeoutException: The client could not finish the operation within specified maximum execution timeout.
        at com.microsoft.azure.storage.core.ExecutionEngine.setupStorageRequest(ExecutionEngine.java:286) ~[azure-storage-7.0.0.jar:?]
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:80) ~[azure-storage-7.0.0.jar:?]
        at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:109) ~[azure-storage-7.0.0.jar:?]
        ... 10 more

```
This is coming from logstash 5.6.10, running plugin logstash-input-azure_event_hubs (1.0.4) on "Ubuntu 16.04.4 LTS"
Thank you

**Comment by robbavey** [comment]
@EmFl Does the Logstash instance recover, or does it permanently stop listening to that partition until a restart occurs?

**Comment by robbavey** [comment]
@EmFl A new version of this plugin (`1.1.0`) has been released. Please update and check if the problem has been fixed

**Comment by robbavey** [comment]
@emFi - I can going to close this issue, as I believe it has been solved as of the latest release. Please reopen if this issue is still occurring with the latest version
