### ISSUE TITLE
ScheduleHandler.run() failed with an error

### ISSUE THREAD

**Issue by aiyerganapathy** [logstash-plugins/logstash-input-azure_event_hubs#37]
I am currently running a logstash instance for a single event hub. This event hub has 4 partitions and it is the built-in end point given by IOT Hub. I am using the following logstash config.

```
input {
    azure_event_hubs {
        type => "azure-logs"
        event_hub_connections => ["<Event Hub Endpoint>"]
        initial_position => "end"
        threads => 5
        decorate_events => true
        storage_connection => "<Connection String>"
   }
}
```
When I tail the logstash logs, I am seeing this error.
```
[2019-05-10T18:10:52,676][INFO ][com.microsoft.azure.eventhubs.impl.ReactorDispatcher] ScheduleHandler.run() failed with an error
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SourceChannelImpl.ensureOpen(SourceChannelImpl.java:154) ~[?:1.8.0_191]
	at sun.nio.ch.SourceChannelImpl.read(SourceChannelImpl.java:158) ~[?:1.8.0_191]
	at com.microsoft.azure.eventhubs.impl.ReactorDispatcher$ScheduleHandler.run(ReactorDispatcher.java:118) [azure-eventhubs-1.3.0.jar:?]
	at com.microsoft.azure.eventhubs.impl.ReactorDispatcher$CloseHandler.run(ReactorDispatcher.java:151) [azure-eventhubs-1.3.0.jar:?]
	at org.apache.qpid.proton.reactor.impl.SelectableImpl.free(SelectableImpl.java:153) [proton-j-0.31.0.jar:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.free(ReactorImpl.java:137) [proton-j-0.31.0.jar:?]
	at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:546) [azure-eventhubs-1.3.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[2019-05-10T18:10:52,677][INFO ][logstash.inputs.azure.processor] Event Hub: sample-iot-hub, Partition: 3 is closing. (reason=Shutdown)
```

This error keeps on happening almost every second and for different partitions.  

Also, if the message was successfully sent to elasticsearch, it appears after a huge delay (sometimes after 15 min).

Please do let me know how to resolve this issue.

**Comment by robbavey** [comment]
@aiyerganapathy I believe this issue should be fixed in the latest version `1.1.2` of this plugin.

I am going to close this issue, but please feel free to reopen if the issue still occurs
