### ISSUE TITLE
com.microsoft.azure.eventhubs.ReceiverDisconnectedException

### ISSUE THREAD

**Issue by cloudeteer** [logstash-plugins/logstash-input-azure_event_hubs#39]
Since upgrading from 6.8 to 7.1.1, the Azure input logstash plugin no long works.
We have also tried OpenJDK 8/11, Sun Java 8/11...same issue :-(

Logstash Release: 7.1.1
Logstash Input: latest

Error:
*****
 Timestamp:2019-05-31T06:53:01 Reference:5422e6c1-bb8d-459c-a634-9fabfe821ff0, TrackingId:a88ed38d-7042-42ee-af30-cd2f3a915c93_B27, SystemTracker:XXXeventhubops:eventhub:insights-operational-logs~8191|cdt_XXXs, Timestamp:2019-05-31T06:53:01 TrackingId:1b034bd73c294e7091df07b9c627c888_G2, SystemTracker:gateway5, Timestamp:2019-05-31T06:53:01, errorContext[NS: XXXeventhubops.servicebus.windows.net, PATH: insights-operational-logs/ConsumerGroups/cdt_XXX/Partitions/0, REFERENCE_ID: a7a0a0_c888_G2_1559285581419]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
        at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:98) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessageReceiver.cancelOpen(MessageReceiver.java:357) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessageReceiver.onOpenComplete(MessageReceiver.java:347) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:414) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:736) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:74) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:113) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:48) ~[azure-eventhubs-2.2.0.jar:?]
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.0.jar:?]
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.0.jar:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.0.jar:?]
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:507) ~[azure-eventhubs-2.2.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: A receiver with a higher epoch '37253' already exists. A new receiver with epoch 474 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:641c4115-4295-4853-a7aa-d929dd4f796f_B27, SystemTracker:XXXXeventhubops:eventhub:insights-operational-logs~8191|cdt_XXXX, Timestamp:2019-05-31T06:53:01 Reference:5422e6c1-bb8d-459c-a634-9fabfe821ff0, TrackingId:a88ed38d-7042-42ee-af30-cd2f3a915c93_B27, SystemTracker:edelageventhubops:eventhub:insights-operational-logs~8191|cdt_XXX, Timestamp:2019-05-31T06:53:01 TrackingId:1b034bd73c294e7091df07b9c627c888_G2, SystemTracker:gateway5, Timestamp:2019-05-31T06:53:01, errorContext[NS: edelageventhubops.servicebus.windows.net, PATH: insights-operational-logs/ConsumerGroups/XXX/Partitions/0, REFERENCE_ID: a7a0a0_c888_G2_1559285581419]
        at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:35) ~[azure-eventhubs-2.2.0.jar:?]
        at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:735) ~[azure-eventhubs-2.2.0.jar:?]
        ... 14 more

**Comment by cskowronnek** [comment]
Same here!
